######################################################################
# Automatically generated by qmake (3.1) Tue Jan 7 00:18:09 2025
######################################################################

TEMPLATE = aux

DISTFILES += \
    linux-x64/build.sh \
    linux-x64/pack.sh \
    linux-x64/rebuild.sh
