#ifndef KEY_DEFINE_H
#define KEY_DEFINE_H

// 0使用系统按键输入，1使用自定义按键
#define KEY_INPUT_MODE 0

enum KEY_DEFINE_INPUT{  
    KEY_DEFINE_INPUT_0,
    KEY_DEFINE_INPUT_1,
    KEY_DEFINE_INPUT_2,
    KEY_DEFINE_INPUT_3,
    KEY_DEFINE_INPUT_4,
    KEY_DEFINE_INPUT_5,
    KEY_DEFINE_INPUT_6,
    KEY_DEFINE_INPUT_7,
    KEY_DEFINE_INPUT_8,
    KEY_DEFINE_INPUT_9,
    KEY_DEFINE_INPUT_UP,
    KEY_DEFINE_INPUT_DOWN,
    KEY_DEFINE_INPUT_LEFT,
    KEY_DEFINE_INPUT_RIGHT,
    KEY_DEFINE_INPUT_ENTER, // enter
    KEY_DEFINE_INPUT_BACK, // backspace
    KEY_DEFINE_INPUT_ESC, // esc
    KEY_DEFINE_INPUT_HOME, // home
    KEY_DEFINE_INPUT_SPACE, // #,space
    KEY_DEFINE_INPUT_STAR, // *

    KEY_DEFINE_INPUT_A,
    KEY_DEFINE_INPUT_B,
    KEY_DEFINE_INPUT_C,
    KEY_DEFINE_INPUT_D,
    KEY_DEFINE_INPUT_E,
    KEY_DEFINE_INPUT_F,
    KEY_DEFINE_INPUT_G,
    KEY_DEFINE_INPUT_H,
    KEY_DEFINE_INPUT_I,
    KEY_DEFINE_INPUT_J,
    KEY_DEFINE_INPUT_K,
    KEY_DEFINE_INPUT_L,
    KEY_DEFINE_INPUT_M,
    KEY_DEFINE_INPUT_N,
    KEY_DEFINE_INPUT_O,
    KEY_DEFINE_INPUT_P,
    KEY_DEFINE_INPUT_Q,
    KEY_DEFINE_INPUT_R,
    KEY_DEFINE_INPUT_S,
    KEY_DEFINE_INPUT_T,
    KEY_DEFINE_INPUT_U,
    KEY_DEFINE_INPUT_V,
    KEY_DEFINE_INPUT_W,
    KEY_DEFINE_INPUT_X,
    KEY_DEFINE_INPUT_Y,
    KEY_DEFINE_INPUT_Z,
    KEY_DEFINE_INPUT_Shift,
    KEY_DEFINE_INPUT_CapsLocks,
    KEY_DEFINE_INPUT_Tab,
    KEY_DEFINE_INPUT_Alt,
    KEY_DEFINE_INPUT_Ctrl,
};

/* 选择输入法:
 * 0:按键
 * 1:虚拟输入法1
 * 2:虚拟输入法2
 * */
extern int input_mode_select;

#endif // KEY_DEFINE_H
